### PR TITLE
Install pyparsing

### PR DESCRIPTION
**Pull request by kpet**
Now required to build the Vulkan specifications (scripts/parse_dependency.py)

Signed-off-by: Kevin Petit <kevin.petit@arm.com>

### CODE REVIEW

**Comment by kpet** [comment]
Should this be done in the vulkan-docs images instead?

**Comment by oddhack** [comment]
I think you may be experiencing a Docker caching issue? The current asciidoctor-spec image has pyparsing installed, though not explicit in the Dockerfile:

$ docker run -it --rm khronosgroup/docker-images@sha256:278e239fecc0ae30be582c8c639783d4245ec61e00967ce8008a4cf0eb478a0a pip3 list | grep pyparsing  
> pyparsing          2.4.7

However, we've experienced some severe and AFAICT, unfixable issues with various gitlab / github CI systems not updating the image they pull after we push new ones to Dockerhub - which is why the Vulkan CI scripts now reference specific image SHAs. Possibly that's what you're experiencing?

> Should this be done in the vulkan-docs images instead?

No. That's legacy at this point, hopefully can be removed entirely eventually.

**Comment by kpet** [comment]
>However, we've experienced some severe and AFAICT, unfixable issues with various gitlab / github CI systems not updating the image they pull after we push new ones to Dockerhub - which is why the Vulkan CI scripts now reference specific image SHAs. Possibly that's what you're experiencing?

Right, that's good to know, thanks! This is likely what I'm experiencing. I'll investigate with that in mind.

Closing this PR since the images apparently already have pyparsing.

**Comment by rpavlik** [comment]
Yep, that's exactly why we started using numbers 😁 didn't occur to me to use hashes to be honest but that's a better idea I think.

**Comment by oddhack** [comment]
> Yep, that's exactly why we started using numbers grin didn't occur to me to use hashes to be honest but that's a better idea I think.

N.b. I actually learned about that trick in a response to my ranting on my FB :-)

**Pull request closed without merging**
